### ISSUE TITLE
Submission Checklist

### ISSUE THREAD

**Issue by StreamOfMaya** [Zondax/ledger-casper#7]
**Submission checklist**

- [ ] 2 Icons (for Ledger device and Ledger Manager)
- [ ] Companion app (binaries or package, for Windows/MacOS/Linux)
- [ ] Contact information 
- [ ] Link to tutorial hosted on third party website
- [ ] Video of your application running on the Ledger device

**Comment by goral09** [comment]
Submission has been completed on 10th of September.
